language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

dist: xenial

install:
  - pip install -r requirements.txt
  - pip install pytest==5.1.0
  - pip install codecov==2.0.15
  - pip install pytest-cov==2.7.1

script:
  - pytest --cov-report term --cov={{ cookiecutter.package_name }} tests/

after_success:
  - codecov
